"""เพิ่มtext Audit Log

Revision ID: 979070a0e887
Revises: b990f5e95503
Create Date: 2026-08-07 11:06:04.085665

"""
from alembic import op
import sqlalchemy as sa


revision = '979070a0e887'
down_revision = 'b990f5e95503'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AuditLogTABLE', 'detail',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('AuditLogTABLE', 'user_agent',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AuditLogTABLE', 'user_agent',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('AuditLogTABLE', 'detail',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
