"""add_actor_username_to_auditlog

Revision ID: d011635287bd
Revises: 3a6ba56cd393
Create Date: 2026-08-31 10:54:20.562180

"""
from alembic import op
import sqlalchemy as sa


revision = 'd011635287bd'
down_revision = '3a6ba56cd393'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AuditLogTABLE', sa.Column('actor_username', sa.String(length=255), nullable=True))
    op.execute(
        """
        UPDATE "AuditLogTABLE"
        SET actor_username = (
            SELECT username 
            FROM "UserTABLE" 
            WHERE "UserTABLE".id = "AuditLogTABLE".user_id
        )
        WHERE user_id IS NOT NULL;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AuditLogTABLE', 'actor_username')
    # ### end Alembic commands ###
