"""Add GIN trigram index for license_plate

Revision ID: 49e5176c8916
Revises: 830b7c11c98f
Create Date: 2026-09-02 13:16:58.013833

"""
from alembic import op
import sqlalchemy as sa


revision = '49e5176c8916'
down_revision = '830b7c11c98f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_BlacklistTABLE_license_plate_trgm', 'BlacklistTABLE', ['license_plate'], unique=False, postgresql_using='gin', postgresql_ops={'license_plate': 'gin_trgm_ops'})
    op.create_index('ix_CarTABLE_license_plate_trgm', 'CarTABLE', ['license_plate'], unique=False, postgresql_using='gin', postgresql_ops={'license_plate': 'gin_trgm_ops'})
    op.create_index('ix_WhitelistTABLE_license_plate_trgm', 'WhitelistTABLE', ['license_plate'], unique=False, postgresql_using='gin', postgresql_ops={'license_plate': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_WhitelistTABLE_license_plate_trgm', table_name='WhitelistTABLE', postgresql_using='gin', postgresql_ops={'license_plate': 'gin_trgm_ops'})
    op.drop_index('ix_CarTABLE_license_plate_trgm', table_name='CarTABLE', postgresql_using='gin', postgresql_ops={'license_plate': 'gin_trgm_ops'})
    op.drop_index('ix_BlacklistTABLE_license_plate_trgm', table_name='BlacklistTABLE', postgresql_using='gin', postgresql_ops={'license_plate': 'gin_trgm_ops'})
    # ### end Alembic commands ###
