"""Add composite index for village and time_detect on CarTABLE

Revision ID: 830b7c11c98f
Revises: f2bab88485ab
Create Date: 2026-09-02 13:07:29.244034

"""
from alembic import op
import sqlalchemy as sa


revision = '830b7c11c98f'
down_revision = 'f2bab88485ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_CarTABLE_village_time', 'CarTABLE', ['village_id', 'time_detect'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_CarTABLE_village_time', table_name='CarTABLE')
    # ### end Alembic commands ###
