"""เพิ่ม category และ name ใน whitelist

Revision ID: 1c1e4ae7996b
Revises: 755fc1911ad0
Create Date: 2026-08-18 10:12:22.358267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '1c1e4ae7996b'
down_revision = '755fc1911ad0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    whitelist_category = postgresql.ENUM('resident', 'regular', 'guest', name='whitelist_category')
    whitelist_category.create(op.get_bind())
    op.add_column('WhitelistTABLE', sa.Column('category', whitelist_category, nullable=False))
    op.add_column('WhitelistTABLE', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WhitelistTABLE', 'name')
    op.drop_column('WhitelistTABLE', 'category')
    postgresql.ENUM(name='whitelist_category').drop(op.get_bind())
    # ### end Alembic commands ###
