"""Email

Revision ID: fa22800b9348
Revises: cfe96bd371bb
Create Date: 2026-08-27 11:50:34.854331

"""
from alembic import op
import sqlalchemy as sa


revision = 'fa22800b9348'
down_revision = 'cfe96bd371bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VerifyTABLE', sa.Column('new_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('VerifyTABLE', 'new_email')
    # ### end Alembic commands ###
