"""add address to village

Revision ID: 3a6ba56cd393
Revises: 25bf6331a93a
Create Date: 2026-08-28 16:23:53.993620

"""
from alembic import op
import sqlalchemy as sa


revision = '3a6ba56cd393'
down_revision = '25bf6331a93a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacttable_user_id'), table_name='ContactTABLE')
    op.create_index(op.f('ix_ContactTABLE_user_id'), 'ContactTABLE', ['user_id'], unique=False)
    op.add_column('GroupTABLE', sa.Column('address', sa.String(length=255), server_default='-', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GroupTABLE', 'address')
    op.drop_index(op.f('ix_ContactTABLE_user_id'), table_name='ContactTABLE')
    op.create_index(op.f('ix_contacttable_user_id'), 'ContactTABLE', ['user_id'], unique=False)
    # ### end Alembic commands ###
