"""add is_online to camera

Revision ID: e5fea52599ec
Revises: 09cab5acce80
Create Date: 2026-09-07 14:03:06.046726

"""
from alembic import op
import sqlalchemy as sa


revision = 'e5fea52599ec'
down_revision = '09cab5acce80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_AuditLogTABLE_created_at'), 'AuditLogTABLE', ['created_at'], unique=False)
    op.create_index(op.f('ix_BlacklistTABLE_created_at'), 'BlacklistTABLE', ['created_at'], unique=False)
    op.add_column('CameraTABLE', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.create_index('ix_notificationtable_user_created', 'NotificationTABLE', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_WhitelistTABLE_created_at'), 'WhitelistTABLE', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_WhitelistTABLE_created_at'), table_name='WhitelistTABLE')
    op.drop_index('ix_notificationtable_user_created', table_name='NotificationTABLE')
    op.drop_column('CameraTABLE', 'is_online')
    op.drop_index(op.f('ix_BlacklistTABLE_created_at'), table_name='BlacklistTABLE')
    op.drop_index(op.f('ix_AuditLogTABLE_created_at'), table_name='AuditLogTABLE')
    # ### end Alembic commands ###
