"""Add unique constraint for village_id and camera name

Revision ID: f2bab88485ab
Revises: d518624090bb
Create Date: 2026-09-02 10:31:18.605851

"""
from alembic import op
import sqlalchemy as sa


revision = 'f2bab88485ab'
down_revision = 'd518624090bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_CameraTABLE_village_id_name', 'CameraTABLE', ['village_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_CameraTABLE_village_id_name', 'CameraTABLE', type_='unique')
    # ### end Alembic commands ###
