"""init schema

Revision ID: b990f5e95503
Revises: 
Create Date: 2026-08-05 14:19:47.434930

"""
from alembic import op
import sqlalchemy as sa


revision = 'b990f5e95503'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GroupTABLE',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_GroupTABLE'))
    )
    op.create_table('CameraTABLE',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('village_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(precision=53), nullable=False),
    sa.Column('long', sa.Float(precision=53), nullable=False),
    sa.Column('stream_ai', sa.String(length=255), nullable=False),
    sa.Column('ai_vision_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['GroupTABLE.id'], name=op.f('fk_CameraTABLE_village_id_GroupTABLE')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_CameraTABLE'))
    )
    op.create_index(op.f('ix_CameraTABLE_village_id'), 'CameraTABLE', ['village_id'], unique=False)
    op.create_table('UserTABLE',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.Column('hashpassword', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'superadmin', name='user_role'), nullable=False),
    sa.Column('village_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verify', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'superadmin' AND village_id IS NULL) OR (role != 'superadmin' AND village_id IS NOT NULL)", name=op.f('ck_UserTABLE_user_village_id_matches_role')),
    sa.ForeignKeyConstraint(['village_id'], ['GroupTABLE.id'], name=op.f('fk_UserTABLE_village_id_GroupTABLE')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_UserTABLE')),
    sa.UniqueConstraint('email', name=op.f('uq_UserTABLE_email')),
    sa.UniqueConstraint('username', name=op.f('uq_UserTABLE_username'))
    )
    op.create_index(op.f('ix_UserTABLE_village_id'), 'UserTABLE', ['village_id'], unique=False)
    op.create_table('AuditLogTABLE',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('village_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['UserTABLE.id'], name=op.f('fk_AuditLogTABLE_user_id_UserTABLE')),
    sa.ForeignKeyConstraint(['village_id'], ['GroupTABLE.id'], name=op.f('fk_AuditLogTABLE_village_id_GroupTABLE')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_AuditLogTABLE'))
    )
    op.create_index(op.f('ix_AuditLogTABLE_user_id'), 'AuditLogTABLE', ['user_id'], unique=False)
    op.create_index(op.f('ix_AuditLogTABLE_village_id'), 'AuditLogTABLE', ['village_id'], unique=False)
    op.create_table('BlacklistTABLE',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('village_id', sa.UUID(), nullable=False),
    sa.Column('license_plate', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['UserTABLE.id'], name=op.f('fk_BlacklistTABLE_added_by_UserTABLE')),
    sa.ForeignKeyConstraint(['village_id'], ['GroupTABLE.id'], name=op.f('fk_BlacklistTABLE_village_id_GroupTABLE')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_BlacklistTABLE'))
    )
    op.create_index(op.f('ix_BlacklistTABLE_added_by'), 'BlacklistTABLE', ['added_by'], unique=False)
    op.create_index('ix_blacklisttable_village_plate_province', 'BlacklistTABLE', ['village_id', 'license_plate', 'province'], unique=False)
    op.create_table('CarTABLE',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('license_plate', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('image_crop', sa.String(length=255), nullable=False),
    sa.Column('image_full', sa.String(length=255), nullable=False),
    sa.Column('time_detect', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_blacklist', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['CameraTABLE.id'], name=op.f('fk_CarTABLE_camera_id_CameraTABLE')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_CarTABLE'))
    )
    op.create_index(op.f('ix_CarTABLE_camera_id'), 'CarTABLE', ['camera_id'], unique=False)
    op.create_index(op.f('ix_CarTABLE_event_id'), 'CarTABLE', ['event_id'], unique=True)
    op.create_index(op.f('ix_CarTABLE_license_plate'), 'CarTABLE', ['license_plate'], unique=False)
    op.create_index(op.f('ix_CarTABLE_time_detect'), 'CarTABLE', ['time_detect'], unique=False)
    op.create_table('ContactTABLE',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('phone', 'line', 'facebook', 'instagram', 'email', 'other', name='contact_type'), nullable=False),
    sa.Column('custom_label', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['UserTABLE.id'], name=op.f('fk_ContactTABLE_user_id_UserTABLE')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ContactTABLE'))
    )
    op.create_index(op.f('ix_ContactTABLE_user_id'), 'ContactTABLE', ['user_id'], unique=False)
    op.create_table('RefreshTABLE',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['UserTABLE.id'], name=op.f('fk_RefreshTABLE_user_id_UserTABLE')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_RefreshTABLE'))
    )
    op.create_index(op.f('ix_RefreshTABLE_token_hash'), 'RefreshTABLE', ['token_hash'], unique=False)
    op.create_index(op.f('ix_RefreshTABLE_user_id'), 'RefreshTABLE', ['user_id'], unique=False)
    op.create_table('VerifyTABLE',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('INITIAL_SETUP', 'PASSWORD_RESET', name='verify_type'), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['UserTABLE.id'], name=op.f('fk_VerifyTABLE_user_id_UserTABLE')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_VerifyTABLE'))
    )
    op.create_index(op.f('ix_VerifyTABLE_token_hash'), 'VerifyTABLE', ['token_hash'], unique=False)
    op.create_index(op.f('ix_VerifyTABLE_user_id'), 'VerifyTABLE', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_VerifyTABLE_user_id'), table_name='VerifyTABLE')
    op.drop_index(op.f('ix_VerifyTABLE_token_hash'), table_name='VerifyTABLE')
    op.drop_table('VerifyTABLE')
    op.drop_index(op.f('ix_RefreshTABLE_user_id'), table_name='RefreshTABLE')
    op.drop_index(op.f('ix_RefreshTABLE_token_hash'), table_name='RefreshTABLE')
    op.drop_table('RefreshTABLE')
    op.drop_index(op.f('ix_ContactTABLE_user_id'), table_name='ContactTABLE')
    op.drop_table('ContactTABLE')
    op.drop_index(op.f('ix_CarTABLE_time_detect'), table_name='CarTABLE')
    op.drop_index(op.f('ix_CarTABLE_license_plate'), table_name='CarTABLE')
    op.drop_index(op.f('ix_CarTABLE_event_id'), table_name='CarTABLE')
    op.drop_index(op.f('ix_CarTABLE_camera_id'), table_name='CarTABLE')
    op.drop_table('CarTABLE')
    op.drop_index('ix_blacklisttable_village_plate_province', table_name='BlacklistTABLE')
    op.drop_index(op.f('ix_BlacklistTABLE_added_by'), table_name='BlacklistTABLE')
    op.drop_table('BlacklistTABLE')
    op.drop_index(op.f('ix_AuditLogTABLE_village_id'), table_name='AuditLogTABLE')
    op.drop_index(op.f('ix_AuditLogTABLE_user_id'), table_name='AuditLogTABLE')
    op.drop_table('AuditLogTABLE')
    op.drop_index(op.f('ix_UserTABLE_village_id'), table_name='UserTABLE')
    op.drop_table('UserTABLE')
    op.drop_index(op.f('ix_CameraTABLE_village_id'), table_name='CameraTABLE')
    op.drop_table('CameraTABLE')
    op.drop_table('GroupTABLE')
    # ### end Alembic commands ###
