"""column camera

Revision ID: 5ffcf3a95123
Revises: 9d3b1f2a6e7c
Create Date: 2026-08-25 16:23:22.528094

"""
from alembic import op
import sqlalchemy as sa


revision = '5ffcf3a95123'
down_revision = '9d3b1f2a6e7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CameraTABLE', 'stream_ai',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CameraTABLE', 'stream_ai',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
