"""Add village_name snapshot to CarTABLE

Revision ID: ff7313572625
Revises: 49e5176c8916
Create Date: 2026-09-02 15:05:08.150445

"""
from alembic import op
import sqlalchemy as sa


revision = 'ff7313572625'
down_revision = '49e5176c8916'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CarTABLE', sa.Column('village_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CarTABLE', 'village_name')
    # ### end Alembic commands ###
