"""เพิ่ม whitelist

Revision ID: 755fc1911ad0
Revises: 243572ed46e7
Create Date: 2026-08-17 17:12:21.303628

"""
from alembic import op
import sqlalchemy as sa


revision = '755fc1911ad0'
down_revision = '243572ed46e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WhitelistTABLE',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('village_id', sa.UUID(), nullable=False),
    sa.Column('license_plate', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['UserTABLE.id'], name=op.f('fk_WhitelistTABLE_added_by_UserTABLE'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['village_id'], ['GroupTABLE.id'], name=op.f('fk_WhitelistTABLE_village_id_GroupTABLE')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_WhitelistTABLE'))
    )
    op.create_index(op.f('ix_WhitelistTABLE_added_by'), 'WhitelistTABLE', ['added_by'], unique=False)
    op.create_index('ix_whitelisttable_village_plate_province', 'WhitelistTABLE', ['village_id', 'license_plate', 'province'], unique=True)
    op.add_column('CarTABLE', sa.Column('is_whitelist', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CarTABLE', 'is_whitelist')
    op.drop_index('ix_whitelisttable_village_plate_province', table_name='WhitelistTABLE')
    op.drop_index(op.f('ix_WhitelistTABLE_added_by'), table_name='WhitelistTABLE')
    op.drop_table('WhitelistTABLE')
    # ### end Alembic commands ###
