"""add index on car license plate and province

Revision ID: 09cab5acce80
Revises: ff7313572625
Create Date: 2026-09-04 14:58:28.794613

"""
from alembic import op
import sqlalchemy as sa


revision = '09cab5acce80'
down_revision = 'ff7313572625'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_BlacklistTABLE_village_id_GroupTABLE'), 'BlacklistTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_BlacklistTABLE_village_id_GroupTABLE'), 'BlacklistTABLE', 'GroupTABLE', ['village_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_CameraTABLE_village_id_GroupTABLE'), 'CameraTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_CameraTABLE_village_id_GroupTABLE'), 'CameraTABLE', 'GroupTABLE', ['village_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_CarTABLE_license_plate_province', 'CarTABLE', ['license_plate', 'province'], unique=False)
    op.drop_constraint(op.f('fk_WhitelistTABLE_village_id_GroupTABLE'), 'WhitelistTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_WhitelistTABLE_village_id_GroupTABLE'), 'WhitelistTABLE', 'GroupTABLE', ['village_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_WhitelistTABLE_village_id_GroupTABLE'), 'WhitelistTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_WhitelistTABLE_village_id_GroupTABLE'), 'WhitelistTABLE', 'GroupTABLE', ['village_id'], ['id'])
    op.drop_index('ix_CarTABLE_license_plate_province', table_name='CarTABLE')
    op.drop_constraint(op.f('fk_CameraTABLE_village_id_GroupTABLE'), 'CameraTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_CameraTABLE_village_id_GroupTABLE'), 'CameraTABLE', 'GroupTABLE', ['village_id'], ['id'])
    op.drop_constraint(op.f('fk_BlacklistTABLE_village_id_GroupTABLE'), 'BlacklistTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_BlacklistTABLE_village_id_GroupTABLE'), 'BlacklistTABLE', 'GroupTABLE', ['village_id'], ['id'])
    # ### end Alembic commands ###
