"""เพิ่มคอลัมใน camera

Revision ID: 243572ed46e7
Revises: 979070a0e887
Create Date: 2026-08-17 14:51:22.681716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '243572ed46e7'
down_revision = '979070a0e887'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_AuditLogTABLE_user_id_UserTABLE'), 'AuditLogTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_AuditLogTABLE_user_id_UserTABLE'), 'AuditLogTABLE', 'UserTABLE', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('BlacklistTABLE', 'added_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_blacklisttable_village_plate_province'), table_name='BlacklistTABLE')
    op.create_index('ix_blacklisttable_village_plate_province', 'BlacklistTABLE', ['village_id', 'license_plate', 'province'], unique=True)
    op.drop_constraint(op.f('fk_BlacklistTABLE_added_by_UserTABLE'), 'BlacklistTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_BlacklistTABLE_added_by_UserTABLE'), 'BlacklistTABLE', 'UserTABLE', ['added_by'], ['id'], ondelete='SET NULL')
    camera_verification_status = postgresql.ENUM('pending', 'verified', 'failed',name='camera_verification_status',)
    camera_verification_status.create(op.get_bind())
    op.add_column('CameraTABLE', sa.Column('verification_status', camera_verification_status, server_default='pending', nullable=False))
    op.drop_constraint(op.f('fk_ContactTABLE_user_id_UserTABLE'), 'ContactTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ContactTABLE_user_id_UserTABLE'), 'ContactTABLE', 'UserTABLE', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_RefreshTABLE_user_id_UserTABLE'), 'RefreshTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_RefreshTABLE_user_id_UserTABLE'), 'RefreshTABLE', 'UserTABLE', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_VerifyTABLE_user_id_UserTABLE'), 'VerifyTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_VerifyTABLE_user_id_UserTABLE'), 'VerifyTABLE', 'UserTABLE', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_VerifyTABLE_user_id_UserTABLE'), 'VerifyTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_VerifyTABLE_user_id_UserTABLE'), 'VerifyTABLE', 'UserTABLE', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_RefreshTABLE_user_id_UserTABLE'), 'RefreshTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_RefreshTABLE_user_id_UserTABLE'), 'RefreshTABLE', 'UserTABLE', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_ContactTABLE_user_id_UserTABLE'), 'ContactTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ContactTABLE_user_id_UserTABLE'), 'ContactTABLE', 'UserTABLE', ['user_id'], ['id'])
    op.drop_column('CameraTABLE', 'verification_status')
    postgresql.ENUM(name='camera_verification_status').drop(op.get_bind())
    op.drop_constraint(op.f('fk_BlacklistTABLE_added_by_UserTABLE'), 'BlacklistTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_BlacklistTABLE_added_by_UserTABLE'), 'BlacklistTABLE', 'UserTABLE', ['added_by'], ['id'])
    op.drop_index('ix_blacklisttable_village_plate_province', table_name='BlacklistTABLE')
    op.create_index(op.f('ix_blacklisttable_village_plate_province'), 'BlacklistTABLE', ['village_id', 'license_plate', 'province'], unique=False)
    op.alter_column('BlacklistTABLE', 'added_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('fk_AuditLogTABLE_user_id_UserTABLE'), 'AuditLogTABLE', type_='foreignkey')
    op.create_foreign_key(op.f('fk_AuditLogTABLE_user_id_UserTABLE'), 'AuditLogTABLE', 'UserTABLE', ['user_id'], ['id'])
    # ### end Alembic commands ###
